services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    environment:
      - RACK_ENV=${RACK_ENV}
      - ALLOWED_API_TOKENS=${ALLOWED_API_TOKENS}
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_TOKEN=${VITE_API_TOKEN}
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
