source 'https://rubygems.org'

gem 'grape', '~> 2.2.0'
gem 'rackup', '~> 2.2'
gem 'puma', '~> 6.5'

group :development, :test do
  gem 'rubocop', require: false
  gem 'debug', require: false
  gem 'rspec', require: false
end