source "https://rubygems.org"

gem "grape", "~> 2.2.0"
gem "rackup", "~> 2.2"
gem "puma", "~> 6.5"
gem "anthropic", "~> 0.3.2"
gem "rack-cors", "~> 2.0"
gem "activemodel", "~> 8.0"
gem "retryable", "~> 3.0"

group :development, :test do
  gem "debug", '~> 1', require: false
  gem "rspec", '~> 3', require: false
  gem "climate_control", "~> 1.2"
end
